# Generated by Django 5.2 on 2025-04-25 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('rtsp_url', models.CharField(max_length=200)),
            ],
            bases=('devices.device',),
        ),
    ]
