# Generated by Django 5.2 on 2025-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='privacy_mode',
            field=models.BooleanField(default=True),
        ),
    ]
