# Generated by Django 5.2 on 2025-04-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_camera_privacy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='tag_on',
            field=models.BooleanField(default=True),
        ),
    ]
